Объединила в див и артикль,изменила расположение страницы,и исправила…
dl-academy-edu/sp-zaytseva-polina pull request #8
Opened 2020-01-28 12:11 UTC by Polinarka

… класс с продукты на категории

2020-01-28 15:48 UTC, SergeyPechinov requested changes

2020-01-28 15:48 UTC, SergeyPechinov commented on index.html
> +      </div>
теперь в блоке contacts так-же лежит карта тоже, а это 2 разных блока, нужно было не избавляться от article, а просто div закрыть ниже

2020-01-29 18:45 UTC, Polinarka commented
сверстала 4 слайда,и добавила картинку с кнопками в слайде

2020-02-01 13:23 UTC, SergeyPechinov requested changes

2020-02-01 13:23 UTC, SergeyPechinov commented on index.html
> +      </nav>
footer-title и рейтинг не являются элементами навигации

2020-02-01 13:23 UTC, SergeyPechinov commented on index.html
> +      </nav>
footer-title и копирайт не являются элементами навигации

2020-02-01 13:23 UTC, SergeyPechinov commented on index.html
> +      </nav>
тут вообще нет навигации по сайту

2020-02-04 12:08 UTC, merged